name: K6 Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke-local:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & run Local environment
        run: |
          docker compose up --build -d mock-local
          npx wait-on http://localhost:3000
          docker compose run --rm -e ENV=local k6
          docker compose down --volumes --remove-orphans

      - name: Upload Local reports
        uses: actions/upload-artifact@v4
        with:
          name: k6-reports-local
          path: k6-tests/reports/

  smoke-qa:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: smoke-local
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & run QA environment
        run: |
          docker compose up --build -d mock-qa
          npx wait-on http://localhost:4000
          docker compose run --rm -e ENV=qa k6
          docker compose down --volumes --remove-orphans

      - name: Upload QA reports
        uses: actions/upload-artifact@v4
        with:
          name: k6-reports-qa
          path: k6-tests/reports/